### ISSUE TITLE
Configurable font

### ISSUE THREAD

**Issue by Mel34** [kennylevinsen/wldash#15]
Awesome work with adding configuration file!

In the light of the new and exciting configurable wldash, could the font face also be configurable please?

**Comment by kennylevinsen** [comment]
I'll look into it. Don't know how troublesome it would be to search for and load fonts, plus the configuration necessary to do it.

It is not just font selection that is hardcoded, the fonts themselves are compiled into wldash for simplicity.

**Comment by Mel34** [comment]
I see. Installed fonts can be queried, font paths are standardized, so it's more beneficial not to ship fonts bundled with the program but instead use system fonts.

**Comment by kennylevinsen** [comment]
There are both pros and cons.

Pro is configurability and smaller binary size.

Con is runtime dependencies, increased startup time (no idea how much), and possible issues with font loading and compatibility ("standardized" is a strong word to use in the Linux world. :) ).

I'll look into it, but no idea how much work it will be.

**Comment by LiHRaM** [comment]
I would like to look into this, specifically by using a fontconfig-enabled crate, such as [font-kit](https://crates.io/crates/font-kit). Currently they don't support rusttype, but I think we can patch that upstream.

**Comment by kennylevinsen** [comment]
Closed by https://github.com/kennylevinsen/wldash/pull/30.
