### ISSUE TITLE
wldash toggle-visible displaces displayed surface

### ISSUE THREAD

**Issue by Mel34** [kennylevinsen/wldash#16]
Steps to reproduce:
Run wldash
wldash toggle-visible
wldash toggle-visible

![Screenshot_2019-09-10-120151](https://user-images.githubusercontent.com/13254332/64604676-d7d9c480-d3c2-11e9-97cb-bada82b9982c.png)

**Comment by kennylevinsen** [comment]
I assume that the screenshot is a full-screen screenshot, showing wldash position as being offset (or rather, the upper left corner being centered)?

**Comment by Mel34** [comment]
yes, that is correct

**Comment by kennylevinsen** [comment]
Sorry for the delay.

Fixed in master. Layer size was not correctly re-reported after toggle, so the compositor assumed a 0-sized layer for positioning. The result is that the upper left corner was centered, rather than the entire layer.

**Comment by Mel34** [comment]
No worries, I am grateful for all the improvements whenever you find the time to make them. Thanks for this project.
