### ISSUE TITLE
Feature request: fuzzy search

### ISSUE THREAD

**Issue by alexarice** [kennylevinsen/wldash#19]
Would be really nice if there was the option of having a fuzzy search for the launcher, I misspell things way too often.

**Comment by kennylevinsen** [comment]
It's already fuzzy for untyped characters. It's more tricky to be fuzzy for *typed* characters... If anyone has a good lib/algorithm, I'm okay with adding it. It's not something I feel like inventing myself, though.

In the meantime, a good advice is to find shorter substrings to write (e.g. to launch "Firefox Nightly", I just type "nig"). Less risk of typos.

**Comment by alexarice** [comment]
I was thinking something like https://github.com/lotabout/fuzzy-matcher though I don't actually know how much better it is tbh

**Comment by alexarice** [comment]
I just had a go, this doesn't actually help if you type the wrong character completely so maybe this isn't the best idea

**Comment by kennylevinsen** [comment]
You mean this one?

https://github.com/kennylevinsen/wldash/blob/b94e80c3464aabac61d594ff4b0273ffacd94127/Cargo.toml#L25

:)

**Comment by alexarice** [comment]
fair enough, I should definitely look at stuff harder before making silly issues
