### ISSUE TITLE
Spaces in launcher

### ISSUE THREAD

**Issue by alexarice** [kennylevinsen/wldash#22]
Launcher items are currently separated by spaces and it can be hard to tell what is happening when the desktop items themselves have spaces in. See the following screenshot for an example:

![screenshot43](https://user-images.githubusercontent.com/17208985/65456827-1dc26e00-de42-11e9-914d-bc0cce8b6d0c.png)

Perhaps a double space between items would work better?

**Comment by mehcode** [comment]
Could I suggest an optional (through configuration) leading icon?

**Comment by kennylevinsen** [comment]
The strings are rendered individually, with a 1/4 font_size right margin. I have upped it semi-reluctantly to 1/2. I wanted to keep it at 3/8 for style, but it didn't help enough, so I went for a full 1/2.

Long-term, I am contemplating having a vertical launcher layout (possibly optional)— Think fzf. Individual lines will provide clean separation—this will also help separate list navigation from input field navigation.This will also be more convenient as a calculator interface, with lines showing history.

@mehcode When you say "icon", what do you mean? Just a configurable utf-8 prefix? There is currently no symbol (not even a white-space) in between the elements.

**Comment by mehcode** [comment]
I mean read the .desktop file, pull out the application icon (with some kind of fallback) and render the image in front of each title. I think that'd be neat.

**Comment by kennylevinsen** [comment]
Patches welcome (as long as it is configurable, icons aren't for everyone).
