### ISSUE TITLE
Multiple batteries are not correctly represented

### ISSUE THREAD

**Issue by pedrocr** [kennylevinsen/wldash#27]
My laptop has two batteries. The controller apparently (stupidly) discharges the first battery and then the second. Right now the first is at 5% and the second at 94%. `i3status` correctly calculates that the laptop has 46% battery left. `wldash` seems to just be displaying the 5% of the first battery.

**Comment by LiHRaM** [comment]
This is because the device i3status uses is `DisplayDevice`, whereas wldash uses `BAT0`. I'll submit a PR for this. :)

Am interested to know though, does upower not show `DisplayDevice` on a laptop with only one battery? Can anyone test this? (`upower --enumerate`, look for `DisplayDevice`.)

**Comment by kennylevinsen** [comment]
DisplayDevice is always there.
