### ISSUE TITLE
4 warnings emitted

### ISSUE THREAD

**Issue by ivanottantuno** [kennylevinsen/wldash#40]
Compiling wldash v0.2.0 (/home/xxxxxxxxxxxxxx/wldash)
warning: use of deprecated function `fuzzy_matcher::skim::fuzzy_indices`: Please use SkimMatcherV2 instead
  --> src/widgets/launcher.rs:18:27
   |
18 | use fuzzy_matcher::skim::{fuzzy_indices, fuzzy_match};
   |                           ^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated function `fuzzy_matcher::skim::fuzzy_match`: Please use SkimMatcherV2 instead
  --> src/widgets/launcher.rs:18:42
   |
18 | use fuzzy_matcher::skim::{fuzzy_indices, fuzzy_match};
   |                                          ^^^^^^^^^^^

warning: use of deprecated function `fuzzy_matcher::skim::fuzzy_indices`: Please use SkimMatcherV2 instead
   --> src/widgets/launcher.rs:100:21
    |
100 |                     fuzzy_indices(&m.name.to_lowercase(), &self.input.to_lowercase())
    |                     ^^^^^^^^^^^^^

warning: use of deprecated function `fuzzy_matcher::skim::fuzzy_match`: Please use SkimMatcherV2 instead
   --> src/widgets/launcher.rs:226:27
    |
226 |         if let Some(ma) = fuzzy_match(val, input) {
    |                           ^^^^^^^^^^^

warning: 4 warnings emitted

    Finished release [optimized] target(s) in 5m 29s

**Comment by kennylevinsen** [comment]
Fixed in master.
