### ISSUE TITLE
wldash: refuse to start more than one instance / toggle exit?

### ISSUE THREAD

**Issue by colemickens** [kennylevinsen/wldash#8]
I realize I could do this with a wrapper script, of sorts, but it might be nice to have this functionality baked in?

It would be nice to just be able to tap my bound sway hotkey for `wldash`, scroll on my volume level, and then tap the hotkey again to close it. Or at the very least, it wouldn't open multiple instances as it does now?

**Comment by kennylevinsen** [comment]
There is now an *experimental* "start-or-kill" command: `wldash start-or-kill`.

As with everything, subject to change when I work out the details.
